### ISSUE TITLE
Better Mac settings

### ISSUE THREAD

**Issue by gwerbin** [OpenPeeDeeP/xdg#1]
From https://stackoverflow.com/a/5084892

- `XDG_DATA_DIRS`: `/Library`
- `XDG_DATA_HOME`: `~/Library`
- `XDG_CONFIG_DIRS`: `/Library/Preferences`
- `XDG_CONFIG_HOME`: `~/Library/Preferences`
- `XDG_CACHE_DIRS`: `/Library/Caches`
- `XDG_CACHE_HOME`: `~/Library/Caches`

I use these personally on my Mac and it works very well with the ecosystem.

**Comment by tssva** [comment]
https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1

The Apple development documents seem to support the following mapping.

- `XDG_DATA_DIRS: /Library/Application Support`
- `XDG_DATA_HOME: ~/Library/Application Support`
- `XDG_CONFIG_DIRS: /Library/Application Support`
- `XDG_CONFIG_HOME: ~/Library/Application Support`
- `XDG_CACHE_DIRS: /Library/Caches`
- `XDG_CACHE_HOME: ~/Library/Caches`

**Comment by dixonwille** [comment]
So I know of a few programs using different patterns. Some us `.local` and `.cache`. Others the `Library/Application Support`. I am unaware of the Caches though. I like that latter by @tssva though as it is backed by docs apple made... I am open to look at a PR though? Thanks to the both of you though.

**Comment by dixonwille** [comment]
While I like the discussion, I don't think the above would be best. I had this library in mind for Unix and Windows. And since Mac was based on the Unix system, I would like to stick with what I have here. Also for any projects that may be using this, this is a breaking change and not backward compatible (they should be versioning but who knows anymore).

**Comment by deanishe** [comment]
I would suggest the cache path be changed to reflect the standard macOS location (`~/Library/Caches`).

My reasoning is that changing the cache directory shouldn’t be a breaking change (it’s a cache), and this is where native tools, like clean-my-Mac and backup software, will know how to handle the data.

For example, cloud backup tools on macOS know out-of-the-box to ignore `~/Library/Caches`, but not the Linux-y `~/.cache`. 

Caches can get large, and Mac storage is both tiny by default and expensive to upgrade.

**Comment by dixonwille** [comment]
The more I think about it, I never versioned this and since the introduction for go modules, I think I will introduce a minor version for v0.1.0 for the current head and v0.2.0 for this change so that I can follow standards and it isn't fully released yet (still version 0 release).
