### ISSUE TITLE
FreeBSD and OpenBSD support

### ISSUE THREAD

**Issue by dtluna** [OpenPeeDeeP/xdg#4]
This package supports Linux, but it doesn't support other popular Unix-like OSes.

**Comment by dixonwille** [comment]
I'll look into it when I get a chance. Always open for PRs though!

**Comment by dixonwille** [comment]
So I was looking at it and it doesn't seem clear where these should go (sorry not a *BSD user). Would it be the same as Linux and just add the build flags to it (I use Fedora mainly right now but have come from Arch)?

**Comment by dixonwille** [comment]
Check out #5 and see if that is what you expect @dtluna
